gists:
  - name: Gist 1
    id: 7b21277a82ffac77d18b4bc8af5434a7
    dest: folder1
    files:
      - source: hello.sh
        chmod: +x
      - source: hello.md
        dest: folder2
        name: hi.md
  - name: Git flow
    id: 5903617
    dest: git-flow
    files:
      - source: README.md
      - source: "Git Flow.md"
